# Generated by Django 4.2.3 on 2023-07-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('single', models.BooleanField()),
                ('ac', models.BooleanField()),
                ('balcony', models.BooleanField()),
                ('attached_bathroom', models.BooleanField()),
                ('approved', models.BooleanField(default=False)),
                ('sign_up_link', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
