# Generated by Django 4.2.3 on 2023-07-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_certificate',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(choices=[('a+', 'A+ve'), ('a-', 'A-ve'), ('b+', 'B+ve'), ('b-', 'B-ve'), ('ab+', 'AB+ve'), ('ab-', 'AB-ve'), ('o+', 'O+ve'), ('o-', 'O-ve')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nid',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
