# Generated by Django 4.2.3 on 2023-07-28 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='MealMonthlyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.SmallIntegerField(choices=[(0, 'Lunch'), (1, 'Dinner')])),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('Saturday', models.CharField(max_length=100)),
                ('Sunday', models.CharField(max_length=100)),
                ('Monday', models.CharField(max_length=100)),
                ('Tuesday', models.CharField(max_length=100)),
                ('Wednesday', models.CharField(max_length=100)),
                ('Thursday', models.CharField(max_length=100)),
                ('Friday', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=10)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double')], max_length=10)),
                ('ac', models.BooleanField(choices=[(False, 'AC'), (True, 'Non-AC')])),
                ('balcony', models.BooleanField()),
                ('attached_bathroom', models.BooleanField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch_default', models.BooleanField(default=True)),
                ('dinner_default', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_app.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double')], max_length=10)),
                ('ac', models.BooleanField(choices=[(False, 'AC'), (True, 'Non-AC')])),
                ('balcony', models.BooleanField()),
                ('attached_bathroom', models.BooleanField()),
                ('status', models.SmallIntegerField(choices=[(-1, 'Pending'), (1, 'Approved'), (0, 'Rejected')], default=-1)),
                ('rejection_reason', models.CharField(max_length=100, null=True)),
                ('assigned_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_app.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('meal_time', models.SmallIntegerField(choices=[(0, 'Lunch'), (1, 'Dinner')])),
                ('on', models.BooleanField(default=True)),
                ('extra_meal', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_app.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LaundryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_app.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LaundryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('shirt', 'Shirt'), ('pant', 'Pant'), ('t-shirt', 'T-Shirt'), ('sweater', 'Sweater'), ('blanket', 'Blanket'), ('bedsheet', 'Bedsheet'), ('pillow cover', 'Pillow Cover')], max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('missing', models.BooleanField(default=False)),
                ('missing_date', models.DateField(blank=True, null=True)),
                ('found', models.BooleanField(default=False)),
                ('found_date', models.DateField(blank=True, null=True)),
                ('laundry_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_app.laundryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Completed')], default=0)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_app.cleaningslots')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_app.tenant')),
            ],
        ),
    ]
