# Generated by Django 4.2.3 on 2023-07-31 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='ac_rent_addition',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='branch',
            name='attached_bathroom_rent_addition',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='branch',
            name='balcony_rent_addition',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='branch',
            name='cleaning_slot_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='branch',
            name='double_room_base_rent',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='branch',
            name='meal_price',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='branch',
            name='single_room_base_rent',
            field=models.IntegerField(default=8000),
        ),
        migrations.AlterField(
            model_name='cleaningslots',
            name='duration',
            field=models.DurationField(default=3),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
