# Generated by Django 4.2.3 on 2023-07-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0003_alter_tenant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrequest',
            name='room_type',
            field=models.SmallIntegerField(choices=[(1, 'Single'), (2, 'Double')]),
        ),
    ]
