# Generated by Django 4.2.3 on 2023-07-31 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_app', '0004_alter_roomrequest_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default='Gulshan Branch', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_requests', related_query_name='room_request', to='tenant_app.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', related_query_name='room', to='tenant_app.branch'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.SmallIntegerField(choices=[(1, 'Single'), (2, 'Double')]),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_requests', related_query_name='room_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', related_query_name='tenant', to='tenant_app.room'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', related_query_name='tenant', to=settings.AUTH_USER_MODEL),
        ),
    ]
