# Generated by Django 4.2.3 on 2023-08-02 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0005_branch_name_roomrequest_branch_alter_room_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningrequest',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenant_app.cleaningslots'),
        ),
        migrations.AlterField(
            model_name='cleaningrequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_requests', related_query_name='cleaning_request', to='tenant_app.tenant'),
        ),
    ]
