# Generated by Django 4.2.3 on 2023-08-02 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0006_alter_cleaningrequest_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningslots',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=10800)),
        ),
    ]
