# Generated by Django 4.2.3 on 2023-08-02 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0007_alter_cleaningslots_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningrequest',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_app.cleaningslots'),
        ),
    ]
