# Generated by Django 4.2.3 on 2023-08-02 01:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0008_alter_cleaningrequest_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryrequest',
            name='completed',
        ),
        migrations.AlterField(
            model_name='laundryitem',
            name='laundry_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_items', related_query_name='laundry_item', to='tenant_app.laundryrequest'),
        ),
        migrations.AlterField(
            model_name='laundryrequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='laundryrequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_requests', related_query_name='laundry_request', to='tenant_app.tenant'),
        ),
    ]
