# Generated by Django 4.2.3 on 2023-08-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0011_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='laundryrequest',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Received'), (2, 'Washing'), (3, 'Drying'), (4, 'Ironing'), (5, 'Ready')]),
        ),
    ]
