# Generated by Django 4.2.3 on 2023-08-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0012_rename_user_feedback_tenant_alter_feedback_feedback'),
        ('tenant_app', '0013_alter_laundryrequest_status'),
    ]

    operations = [
    ]
