# Generated by Django 4.2.3 on 2023-08-13 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_app', '0015_alter_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.SmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.SmallIntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('method', models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Online')])),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', related_query_name='payment', to='tenant_app.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BookingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('paid', models.BooleanField(default=False)),
                ('room_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_fee', related_query_name='booking_fee', to='tenant_app.roomrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_fee', related_query_name='booking_fee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
