# Generated by Django 4.2.3 on 2023-08-13 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_app', '0017_roomrequest_approval_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingfee',
            name='method',
            field=models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Online')], null=True),
        ),
        migrations.AddField(
            model_name='bookingfee',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_fee', related_query_name='booking_fee', to='tenant_app.tenant'),
        ),
        migrations.AddField(
            model_name='bookingfee',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingfee',
            name='room_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_fee', related_query_name='booking_fee', to='tenant_app.roomrequest'),
        ),
        migrations.AlterField(
            model_name='bookingfee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_fee', related_query_name='booking_fee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Online')], null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', related_query_name='payment', to='tenant_app.tenant'),
        ),
    ]
