# Generated by Django 4.2.3 on 2023-08-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0018_bookingfee_method_bookingfee_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingfee',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
