# Generated by Django 4.2.3 on 2023-08-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0019_alter_bookingfee_date_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningslots',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_slots', related_query_name='cleaning_slot', to='tenant_app.branch'),
            preserve_default=False,
        ),
    ]
