# Generated by Django 4.2.3 on 2023-08-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0020_cleaningslots_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryitem',
            name='found',
        ),
        migrations.RemoveField(
            model_name='laundryitem',
            name='found_date',
        ),
        migrations.RemoveField(
            model_name='laundryitem',
            name='missing_date',
        ),
    ]
