# Generated by Django 4.2.3 on 2023-08-15 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0021_remove_laundryitem_found_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundryitem',
            old_name='missing',
            new_name='is_missing',
        ),
    ]
