# Generated by Django 4.2.3 on 2023-08-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0022_rename_missing_laundryitem_is_missing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryitem',
            name='is_missing',
        ),
        migrations.AddField(
            model_name='laundryitem',
            name='missing',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Returned')], default=0),
        ),
    ]
