# Generated by Django 4.2.3 on 2023-08-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0023_remove_laundryitem_is_missing_laundryitem_missing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryitem',
            name='missing',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Found'), (3, 'Returned')], default=0),
        ),
    ]
