# Generated by Django 4.2.3 on 2023-08-15 14:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_app', '0024_alter_laundryitem_missing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='roomrequest',
            name='approval_date',
        ),
        migrations.AddField(
            model_name='bookingfee',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ArchivedTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_app.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_tenants', related_query_name='archived_tenant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
