# Generated by Django 4.2.3 on 2023-08-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0025_remove_leaverequest_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrequest',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
