# Generated by Django 4.2.3 on 2023-08-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0026_alter_roomrequest_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrequest',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='start_date',
            field=models.DateField(),
        ),
    ]
