# Generated by Django 4.2.3 on 2023-08-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0029_alter_leaverequest_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingfee',
            name='archived',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_fee', related_query_name='booking_fee', to='tenant_app.archivedtenant'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='archived',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', related_query_name='payment', to='tenant_app.archivedtenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='start_date',
            field=models.DateField(),
        ),
    ]
