# Generated by Django 4.2.3 on 2023-08-15 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0030_bookingfee_archived_payment_amount_payment_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingfee',
            name='tenant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_fee', related_query_name='booking_fee', to='tenant_app.tenant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', related_query_name='payment', to='tenant_app.tenant'),
        ),
    ]
