# Generated by Django 4.2.3 on 2023-08-15 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0031_alter_bookingfee_tenant_alter_payment_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', related_query_name='meal', to='tenant_app.tenant'),
        ),
    ]
