# Generated by Django 4.2.3 on 2023-08-15 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0033_laundryitem_price_meal_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealmonthlymenu',
            old_name='Friday',
            new_name='thu_lunch',
        ),
        migrations.RenameField(
            model_name='mealmonthlymenu',
            old_name='Monday',
            new_name='tue_dinner',
        ),
        migrations.RenameField(
            model_name='mealmonthlymenu',
            old_name='Saturday',
            new_name='tue_lunch',
        ),
        migrations.RenameField(
            model_name='mealmonthlymenu',
            old_name='Sunday',
            new_name='wed_dinner',
        ),
        migrations.RenameField(
            model_name='mealmonthlymenu',
            old_name='Thursday',
            new_name='wed_lunch',
        ),
        migrations.RemoveField(
            model_name='mealmonthlymenu',
            name='Tuesday',
        ),
        migrations.RemoveField(
            model_name='mealmonthlymenu',
            name='Wednesday',
        ),
        migrations.RemoveField(
            model_name='mealmonthlymenu',
            name='meal_time',
        ),
        migrations.AddField(
            model_name='mealmonthlymenu',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meal_monthly_menus', related_query_name='meal_monthly_menu', to='tenant_app.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealmonthlymenu',
            name='fri_dinner',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealmonthlymenu',
            name='fri_lunch',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealmonthlymenu',
            name='mon_dinner',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealmonthlymenu',
            name='mon_lunch',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealmonthlymenu',
            name='sat_dinner',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealmonthlymenu',
            name='sat_lunch',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealmonthlymenu',
            name='sun_dinner',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealmonthlymenu',
            name='sun_lunch',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealmonthlymenu',
            name='thu_dinner',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
