# Generated by Django 4.2.3 on 2023-08-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0035_alter_roomrequest_assigned_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='laundry_due',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='meal_due',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='rent',
            field=models.IntegerField(default=0),
        ),
    ]
